export const name_to_ticker: { [key: string]: string } = {
    "Apple Inc.": "AAPL",
    "Microsoft Corp": "MSFT",
    "Nvidia Corp": "NVDA",
    "Amazon.com Inc": "AMZN",
    "Meta Platforms, Inc. Class A": "META",
    "Alphabet Inc. Class A": "GOOGL",
    "Berkshire Hathaway Class B": "BRK.B",
    "Alphabet Inc. Class C": "GOOG",
    "Eli Lilly & Co.": "LLY",
    "Broadcom Inc.": "AVGO",
    "Tesla, Inc.": "TSLA",
    "Jpmorgan Chase & Co.": "JPM",
    "Unitedhealth Group Incorporated": "UNH",
    "Exxon Mobil Corporation": "XOM",
    "Visa Inc.": "V",
    "Procter & Gamble Company": "PG",
    "Costco Wholesale Corp": "COST",
    "Mastercard Incorporated": "MA",
    "Johnson & Johnson": "JNJ",
    "Home Depot, Inc.": "HD",
    "Walmart Inc.": "WMT",
    "Abbvie Inc.": "ABBV",
    "Netflix Inc": "NFLX",
    "Merck & Co., Inc.": "MRK",
    "Coca-Cola Company": "KO",
    "Bank of America Corporation": "BAC",
    "Oracle Corp": "ORCL",
    "Salesforce, Inc.": "CRM",
    "Advanced Micro Devices": "AMD",
    "Pepsico, Inc.": "PEP",
    "Chevron Corporation": "CVX",
    "Adobe Inc.": "ADBE",
    "Thermo Fisher Scientific, Inc.": "TMO",
    "Linde Plc": "LIN",
    "Accenture Plc": "ACN",
    "Mcdonald's Corporation": "MCD",
    "Abbott Laboratories": "ABT",
    "Cisco Systems, Inc.": "CSCO",
    "International Business Machines Corporation": "IBM",
    "Ge Aerospace": "GE",
    "Philip Morris International Inc.": "PM",
    "Qualcomm Inc": "QCOM",
    "Verizon Communications": "VZ",
    "Wells Fargo & Co.": "WFC",
    "Intuit Inc": "INTU",
    "Texas Instruments Incorporated": "TXN",
    "Danaher Corporation": "DHR",
    "Servicenow, Inc.": "NOW",
    "Amgen Inc": "AMGN",
    "Intuitive Surgical Inc.": "ISRG",
    "Nextra Energy, Inc.": "NEE",
    "Caterpillar Inc.": "CAT",
    "S&p Global Inc.": "SPGI",
    "Pfizer Inc.": "PFE",
    "The Walt Disney Company": "DIS",
    "Rtx Corporation": "RTX",
    "Applied Materials Inc": "AMAT",
    "Comcast Corp": "CMCSA",
    "At&t Inc.": "T",
    "Goldman Sachs Group Inc.": "GS",
    "Union Pacific Corp.": "UNP",
    "Uber Technologies, Inc.": "UBER",
    "Progressive Corporation": "PGR",
    "American Express Company": "AXP",
    "Lowe's Companies Inc.": "LOW",
    "Tjx Companies, Inc.": "TJX",
    "Booking Holdings Inc.": "BKNG",
    "Honeywell International, Inc.": "HON",
    "Elevance Health, Inc.": "ELV",
    "Stryker Corporation": "SYK",
    "Vertex Pharmaceuticals Inc": "VRTX",
    "Blackrock, Inc.": "BLK",
    "Morgan Stanley": "MS",
    "Eaton Corporation, Plcs": "ETN",
    "Boston Scientific Corp.": "BSX",
    "Regeneron Pharmaceuticals Inc": "REGN",
    "Lockheed Martin Corp.": "LMT",
    "Conocophillips": "COP",
    "Medtronic Plc": "MDT",
    "Prologis, Inc.": "PLD",
    "Chubb Limited": "CB",
    "Automatic Data Processing": "ADP",
    "Marsh & Mclennan Companies, Inc.": "MMC",
    "Palo Alto Networks, Inc.": "PANW",
    "Analog Devices, Inc.": "ADI",
    "Starbucks Corp": "SBUX",
    "American Tower Corporation": "AMT",
    "Citigroup Inc.": "C",
    "Blackstone Inc.": "BX",
    "T-Mobile Us, Inc.": "TMUS",
    "The Cigna Group": "CI",
    "Gilead Sciences Inc": "GILD",
    "Fiserv, Inc.": "FI",
    "Deere & Company": "DE",
    "Mondelez International, Inc. Class A": "MDLZ",
    "Kla Corporation": "KLAC",
    "Micron Technology, Inc.": "MU",
    "Lam Research Corp": "LRCX",
    "Bristol-Myers Squibb Co.": "BMY",
    "The Southern Company": "SO",
    "Nike, Inc.": "NKE",
    "The Charles Schwab Corporation": "SCHW",
    "Intercontinental Exchange Inc.": "ICE",
    "United Parcel Service, Inc. Class B": "UPS",
    "Arista Networks": "ANET",
    "Duke Energy Corporation": "DUK",
    "Boeing Company": "BA",
    "Altria Group, Inc.": "MO",
    "The Sherwin-Williams Company": "SHW",
    "Colgate-Palmolive Company": "CL",
    "Zoetis Inc.": "ZTS",
    "Intel Corp": "INTC",
    "Equinix, Inc. Reit": "EQIX",
    "Trane Technologies Plc": "TT",
    "Kkr & Co. Inc.": "KKR",
    "Cme Group Inc.": "CME",
    "Welltower Inc.": "WELL",
    "Chipotle Mexican Grill, Inc.": "CMG",
    "Hca Healthcare, Inc.": "HCA",
    "Waste Management, Inc.": "WM",
    "Parker-Hannifin Corporation": "PH",
    "Amphenol Corporation": "APH",
    "Transdigm Group Incorporated": "TDG",
    "Aon Plc Class A": "AON",
    "Moody's Corporation": "MCO",
    "Synopsys Inc": "SNPS",
    "3m Company": "MMM",
    "Motorola Solutions, Inc.": "MSI",
    "Paypal Holdings, Inc.": "PYPL",
    "Cadence Design Systems": "CDNS",
    "Cvs Health Corporation": "CVS",
    "Northrop Grumman Corp.": "NOC",
    "Cintas Corp": "CTAS",
    "Pnc Financial Services Group": "PNC",
    "Target Corporation": "TGT",
    "U.S. Bancorp": "USB",
    "General Dynamics Corporation": "GD",
    "Eog Resources, Inc.": "EOG",
    "Illinois Tool Works Inc.": "ITW",
    "Becton, Dickinson and Co.": "BDX",
    "Mckesson Corporation": "MCK",
    "O'reilly Automotive, Inc.": "ORLY",
    "Csx Corporation": "CSX",
    "Fedex Corporation": "FDX",
    "Carrier Global Corporation": "CARR",
    "Arthur J. Gallagher & Co.": "AJG",
    "Ecolab, Inc.": "ECL",
    "Air Products & Chemicals, Inc.": "APD",
    "Newmont Corporation": "NEM",
    "Constellation Energy Corporation": "CEG",
    "Ge Vernova Inc.": "GEV",
    "Freeport-Mcmoran Inc.": "FCX",
    "Crowdstrike Holdings, Inc. Class A": "CRWD",
    "Nxp Semiconductors N.v.": "NXPI",
    "Roper Technologies, Inc.": "ROP",
    "D.R. Horton Inc.": "DHI",
    "Emerson Electric Co.": "EMR",
    "Marathon Petroleum Corporation": "MPC",
    "Schlumberger Limited": "SLB",
    "Public Storage": "PSA",
    "Autodesk Inc": "ADSK",
    "Aflac Inc.": "AFL",
    "Truist Financial Corporation": "TFC",
    "Marriot International Class A": "MAR",
    "Norfolk Southern Corp.": "NSC",
    "Williams Companies Inc.": "WMB",
    "American Electric Power Company, Inc.": "AEP",
    "Realty Income Corporation": "O",
    "The Travelers Companies, Inc.": "TRV",
    "Autozone, Inc.": "AZO",
    "Phillips 66": "PSX",
    "Simon Property Group, Inc.": "SPG",
    "Hilton Worldwide Holdings Inc.": "HLT",
    "Oneok, Inc.": "OKE",
    "Capital One Financial": "COF",
    "General Motors Company": "GM",
    "Ross Stores Inc": "ROST",
    "Sempra": "SRE",
    "Airbnb, Inc. Class A": "ABNB",
    "Crown Castle Inc.": "CCI",
    "Bank of New York Mellon Corporation": "BK",
    "Digital Realty Trust, Inc.": "DLR",
    "Paccar Inc": "PCAR",
    "The Allstate Corporation": "ALL",
    "United Rentals, Inc.": "URI",
    "Dominion Energy, Inc.": "D",
    "Kimberly-Clark Corp.": "KMB",
    "American International Group, Inc.": "AIG",
    "Johnson Controls International Plc": "JCI",
    "Fortinet, Inc.": "FTNT",
    "Fidelity National Information Services, Inc.": "FIS",
    "Fair Isaac Corporation": "FICO",
    "Lennar Corporation Class A": "LEN",
    "Metlife, Inc.": "MET",
    "Kenvue Inc.": "KVUE",
    "Te Connectivity Ltd": "TEL",
    "Msci, Inc.": "MSCI",
    "Ameriprise Financial, Inc.": "AMP",
    "W.W. Grainger, Inc.": "GWW",
    "Valero Energy Corporation": "VLO",
    "Monolithic Power Systems, Inc.": "MPWR",
    "Copart Inc": "CPRT",
    "Iqvia Holdings Inc.": "IQV",
    "L3harris Technologies, Inc.": "LHX",
    "Paychex Inc": "PAYX",
    "Pg&e Corporation": "PCG",
    "Republic Services Inc.": "RSG",
    "Microchip Technology Inc": "MCHP",
    "Prudential Financial, Inc.": "PRU",
    "Public Service Enterprise Group Incorporated": "PEG",
    "General Mills, Inc.": "GIS",
    "Ford Motor Company": "F",
    "Idexx Laboratories Inc": "IDXX",
    "Arch Capital Group Ltd": "ACGL",
    "Edwards Lifesciences Corp": "EW",
    "Cummins Inc.": "CMI",
    "Kinder Morgan, Inc.": "KMI",
    "Constellation Brands, Inc.": "STZ",
    "Centene Corporation": "CNC",
    "Agilent Technologies Inc.": "A",
    "Exelon Corporation": "EXC",
    "Fastenal Co": "FAST",
    "Cencora, Inc.": "COR",
    "Corteva, Inc.": "CTVA",
    "Gartner, Inc.": "IT",
    "Royal Caribbean Group": "RCL",
    "Quanta Services, Inc.": "PWR",
    "Keurig Dr Pepper Inc.": "KDP",
    "Humana Inc.": "HUM",
    "Cognizant Technology Solutions": "CTSH",
    "Ametek, Inc.": "AME",
    "Verisk Analytics, Inc.": "VRSK",
    "Otis Worldwide Corporation": "OTIS",
    "Sysco Corporation": "SYY",
    "Equifax, Incorporated": "EFX",
    "Yum! Brands, Inc.": "YUM",
    "Howmet Aerospace Inc.": "HWM",
    "Extra Space Storage, Inc.": "EXR",
    "Ingersoll Rand Inc.": "IR",
    "Ge Healthcare Technologies Inc.": "GEHC",
    "Resmed Inc.": "RMD",
    "The Kroger Co.": "KR",
    "Consolidated Edison, Inc.": "ED",
    "Monster Beverage Corporation": "MNST",
    "Electronic Arts Inc": "EA",
    "Hess Corporation": "HES",
    "Cbre Group, Inc.": "CBRE",
    "Dow Inc.": "DOW",
    "Vici Properties Inc.": "VICI",
    "Xcel Energy, Inc.": "XEL",
    "The Hartford Financial Services Group, Inc.": "HIG",
    "Old Dominion Freight Line": "ODFL",
    "Nucor Corporation": "NUE",
    "Dupont De Nemours, Inc.": "DD",
    "Iron Mountain Inc.": "IRM",
    "Occidental Petroleum Corporation": "OXY",
    "Charter Comm Inc Del Cl a": "CHTR",
    "Baker Hughes Company": "BKR",
    "Targa Resources Corp.": "TRGP",
    "Avalonbay Communities, Inc.": "AVB",
    "Discover Financial Services": "DFS",
    "Edison International": "EIX",
    "Corning Incorporated": "GLW",
    "Martin Marietta Materials": "MLM",
    "Costar Group Inc": "CSGP",
    "Ebay Inc": "EBAY",
    "Vulcan Materials Company": "VMC",
    "Xylem Inc": "XYL",
    "Diamondback Energy, Inc.": "FANG",
    "On Semiconductor Corp": "ON",
    "Lululemon Athletica Inc.": "LULU",
    "Tractor Supply Co": "TSCO",
    "Wec Energy Group, Inc.": "WEC",
    "Rockwell Automation, Inc.": "ROK",
    "Nasdaq, Inc.": "NDAQ",
    "Willis Towers Watson Public Limited Companys": "WTW",
    "Mettler-Toledo International": "MTD",
    "Archer Daniels Midland Company": "ADM",
    "Ppg Industries, Inc.": "PPG",
    "Nvr, Inc.": "NVR",
    "Pultegroup, Inc.": "PHM",
    "Cdw Corporation": "CDW",
    "Delta Air Lines, Inc.": "DAL",
    "Wabtec Inc.": "WAB",
    "Hp Inc.": "HPQ",
    "The Hershey Company": "HSY",
    "American Water Works Company, Inc": "AWK",
    "Fifth Third Bancorp": "FITB",
    "Biogen Inc.": "BIIB",
    "The Kraft Heinz Company": "KHC",
    "Global Payments, Inc.": "GPN",
    "M&t Bank Corp.": "MTB",
    "Vistra Corp.": "VST",
    "Cardinal Health, Inc.": "CAH",
    "Ansys Inc": "ANSS",
    "Dexcom, Inc.": "DXCM",
    "Entergy Corporation": "ETR",
    "Axon Enterprise, Inc.": "AXON",
    "Equity Residential": "EQR",
    "International Flavors & Fragrances Inc.": "IFF",
    "Garmin Ltd": "GRMN",
    "Keysight Technologies, Inc.": "KEYS",
    "Sba Communications Corp": "SBAC",
    "Ventas, Inc.": "VTR",
    "Dover Corporation": "DOV",
    "Fortive Corporation": "FTV",
    "Dte Energy Company": "DTE",
    "Church & Dwight Co., Inc.": "CHD",
    "Devon Energy Corporation": "DVN",
    "State Street Corporation": "STT",
    "Broadridge Financial Solutions Inc": "BR",
    "Halliburton Company": "HAL",
    "First Solar, Inc.": "FSLR",
    "Brown & Brown, Inc.": "BRO",
    "Tyler Technologies, Inc.": "TYL",
    "Netapp, Inc": "NTAP",
    "Steris Plc": "STE",
    "Veralto Corporation": "VLTO",
    "Take-Two Interactive Software Inc": "TTWO",
    "Deckers Outdoor Corp": "DECK",
    "Ppl Corporation": "PPL",
    "Eversource Energy": "ES",
    "Weyerhaeuser Company": "WY",
    "Lyondellbasell Industries N.v. Class A": "LYB",
    "T Rowe Price Group Inc": "TROW",
    "Super Micro Computer, Inc.": "SMCI",
    "Firstenergy Corp.": "FE",
    "Moderna, Inc.": "MRNA",
    "Builders Firstsource, Inc.": "BLDR",
    "Smurfit Westrock Plc": "SW",
    "West Pharmaceutical Services, Inc.": "WST",
    "Zimmer Biomet Holdings, Inc.": "ZBH",
    "Raymond James Financial, Inc.": "RJF",
    "Cboe Global Markets, Inc.": "CBOE",
    "Hewlett Packard Enterprise Company": "HPE",
    "The Cooper Companies, Inc.": "COO",
    "Ameren Corporation": "AEE",
    "Hubbell Incorporated": "HUBB",
    "Corpay, Inc.": "CPAY",
    "Godaddy Inc": "GDDY",
    "Cincinnati Financial Corp": "CINF",
    "Invitation Homes Inc.": "INVH",
    "Kellanova": "K",
    "Leidos Holdings, Inc.": "LDOS",
    "Mccormick & Company, Incorporated Non-Vtg Cs": "MKC",
    "Western Digital Corp.": "WDC",
    "Molina Healthcare, Inc.": "MOH",
    "Ball Corporation": "BALL",
    "Clorox Company": "CLX",
    "Huntington Bancshares Inc": "HBAN",
    "Ptc, Inc": "PTC",
    "Cms Energy Corporation": "CMS",
    "Regions Financial Corp.": "RF",
    "Atmos Energy Corporation": "ATO",
    "Essex Property Trust, Inc": "ESS",
    "Teledyne Technologies Incorporated": "TDY",
    "Baxter International Inc.": "BAX",
    "Teradyne, Inc.": "TER",
    "Omnicom Group Inc.": "OMC",
    "Seagate Technology Holdings Plcs": "STX",
    "The Estee Lauder Companies Inc. Class A": "EL",
    "Eqt Corp": "EQT",
    "Alexandria Real Estate Equities, Inc.": "ARE",
    "Synchrony Financial": "SYF",
    "Waters Corp": "WAT",
    "Darden Restaurants, Inc.": "DRI",
    "Genuine Parts Company": "GPC",
    "Mid-America Apartment Communities, Inc.": "MAA",
    "Hologic Inc": "HOLX",
    "Best Buy Company, Inc.": "BBY",
    "Warner Bros. Discovery, Inc. Series a": "WBD",
    "Labcorp Holdings Inc.": "LH",
    "Aptiv Plc": "APTV",
    "Packaging Corp of America": "PKG",
    "Citizens Financial Group, Inc.": "CFG",
    "Dollar General Corp.": "DG",
    "Ulta Beauty, Inc.": "ULTA",
    "Northern Trust Corp": "NTRS",
    "Jacobs Solutions Inc.": "J",
    "W.R. Berkley Corporation": "WRB",
    "Principal Financial Group, Inc.": "PFG",
    "Avery Dennison Corp.": "AVY",
    "Centerpoint Energy, Inc.": "CNP",
    "Masco Corporation": "MAS",
    "Tyson Foods, Inc.": "TSN",
    "Align Technology Inc": "ALGN",
    "Carnival Corporation": "CCL",
    "Zebra Technologies Corporation": "ZBRA",
    "Expedia Group, Inc.": "EXPE",
    "Quest Diagnostics Inc.": "DGX",
    "Textron, Inc.": "TXT",
    "Coterra Energy Inc.": "CTRA",
    "Southwest Airlines Co.": "LUV",
    "Expeditors International of Washington, Inc.": "EXPD",
    "Factset Research Systems": "FDS",
    "Nrg Energy, Inc.": "NRG",
    "International Paper Co.": "IP",
    "Steel Dynamics Inc": "STLD",
    "United Airlines Holdings, Inc.": "UAL",
    "Everest Group, Ltd.": "EG",
    "Skyworks Solutions Inc": "SWKS",
    "Insulet Corporation": "PODD",
    "Verisign Inc": "VRSN",
    "Kimco Realty Corp.": "KIM",
    "Healthpeak Properties, Inc.": "DOC",
    "Amcor Plcs": "AMCR",
    "Stanley Black & Decker, Inc.": "SWK",
    "Nisource Inc.": "NI",
    "Conagra Brands, Inc.": "CAG",
    "Keycorp": "KEY",
    "Revvity, Inc.": "RVTY",
    "Alliant Energy Corporation": "LNT",
    "Idex Corporation": "IEX",
    "Pentair Plc": "PNR",
    "Enphase Energy, Inc.": "ENPH",
    "Gen Digital Inc.": "GEN",
    "Akamai Technologies Inc": "AKAM",
    "Snap-on Incorporated": "SNA",
    "Las Vegas Sands Corp.": "LVS",
    "Marathon Oil Corporation": "MRO",
    "Dollar Tree Inc.": "DLTR",
    "Cf Industries Holding, Inc.": "CF",
    "Loews Corporation": "L",
    "Udr, Inc.": "UDR",
    "Universal Health Services, Inc. Class B": "UHS",
    "Rollins, Inc.": "ROL",
    "Bunge Global Sa": "BG",
    "Evergy, Inc.": "EVRG",
    "Trimble Inc.": "TRMB",
    "Domino's Pizza Inc.": "DPZ",
    "Live Nation Entertainment Inc.": "LYV",
    "Viatris Inc.": "VTRS",
    "Pool Corporation": "POOL",
    "Jb Hunt Transport Services Inc": "JBHT",
    "Nordson Corp": "NDSN",
    "Camden Property Trust": "CPT",
    "Henry (Jack) & Associates": "JKHY",
    "Jabil Inc.": "JBL",
    "F5, Inc.": "FFIV",
    "Carmax Inc.": "KMX",
    "Aes Corporation": "AES",
    "Allegion Public Limited Company": "ALLE",
    "The J.M. Smucker Company": "SJM",
    "Juniper Networks Inc": "JNPR",
    "Regency Centers Corporation": "REG",
    "Host Hotels & Resorts, Inc.": "HST",
    "Celanese Corporation": "CE",
    "Eastman Chemical Company": "EMN",
    "The Interpublic Group of Companies, Inc.": "IPG",
    "Bio-Techne Corp.": "TECH",
    "C.H. Robinson Worldwide, Inc.": "CHRW",
    "Teleflex Incorporated": "TFX",
    "Epam Systems, Inc.": "EPAM",
    "Bxp, Inc.": "BXP",
    "Lkq Corporation": "LKQ",
    "Catalent, Inc.": "CTLT",
    "Qorvo, Inc.": "QRVO",
    "Huntington Ingalls Industries, Inc.": "HII",
    "Albemarle Corporation": "ALB",
    "Molson Coors Beverage Company Class B": "TAP",
    "Pinnacle West Capital Corporation": "PNW",
    "Charles River Laboratories International, Inc.": "CRL",
    "Assurant, Inc.": "AIZ",
    "Campbell Soup Company": "CPB",
    "News Corporation Class A": "NWSA",
    "A.O. Smith Corporation": "AOS",
    "Tapestry, Inc.": "TPR",
    "Fox Corporation Class A": "FOXA",
    "Solventum Corporation": "SOLV",
    "Marketaxess Holdings Inc.": "MKTX",
    "Match Group, Inc": "MTCH",
    "Incyte Genomics Inc": "INCY",
    "Hormel Foods Corporation": "HRL",
    "Lamb Weston Holdings, Inc.": "LW",
    "Henry Schein Inc": "HSIC",
    "Mgm Resorts International": "MGM",
    "Dayforce, Inc.": "DAY",
    "Globe Life Inc.": "GL",
    "Davita Inc.": "DVA",
    "Hasbro, Inc.": "HAS",
    "Generac Holdings Inc": "GNRC",
    "The Mosaic Company": "MOS",
    "Apa Corporation": "APA",
    "Federal Realty Investment Trust": "FRT",
    "Brown-Forman Corporation Class B": "BF.B",
    "Caesars Entertainment, Inc.": "CZR",
    "Paycom Software, Inc.": "PAYC",
    "Mohawk Industries, Inc.": "MHK",
    "Norwegian Cruise Line Holdings Ltd.s": "NCLH",
    "Fmc Corporation": "FMC",
    "Wynn Resorts Ltd": "WYNN",
    "Borgwarner Inc.": "BWA",
    "Invesco Ltd": "IVZ",
    "Ralph Lauren Corporation": "RL",
    "American Airlines Group Inc.": "AAL",
    "Bio-Rad Laboratories, Inc.Class A": "BIO",
    "Etsy, Inc.": "ETSY",
    "Walgreens Boots Alliance, Inc": "WBA",
    "Bath & Body Works, Inc.": "BBWI",
    "Franklin Resources, Inc.": "BEN",
    "Paramount Global Class B": "PARA",
    "Fox Corporation Class B": "FOX",
    "News Corporation Class B": "NWS"
};

export const ticker_to_name: { [key: string]: string } = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corp",
    "NVDA": "Nvidia Corp",
    "AMZN": "Amazon.com Inc",
    "META": "Meta Platforms, Inc. Class A",
    "GOOGL": "Alphabet Inc. Class A",
    "BRK.B": "Berkshire Hathaway Class B",
    "GOOG": "Alphabet Inc. Class C",
    "LLY": "Eli Lilly & Co.",
    "AVGO": "Broadcom Inc.",
    "TSLA": "Tesla, Inc.",
    "JPM": "Jpmorgan Chase & Co.",
    "UNH": "Unitedhealth Group Incorporated",
    "XOM": "Exxon Mobil Corporation",
    "V": "Visa Inc.",
    "PG": "Procter & Gamble Company",
    "COST": "Costco Wholesale Corp",
    "MA": "Mastercard Incorporated",
    "JNJ": "Johnson & Johnson",
    "HD": "Home Depot, Inc.",
    "WMT": "Walmart Inc.",
    "ABBV": "Abbvie Inc.",
    "NFLX": "Netflix Inc",
    "MRK": "Merck & Co., Inc.",
    "KO": "Coca-Cola Company",
    "BAC": "Bank of America Corporation",
    "ORCL": "Oracle Corp",
    "CRM": "Salesforce, Inc.",
    "AMD": "Advanced Micro Devices",
    "PEP": "Pepsico, Inc.",
    "CVX": "Chevron Corporation",
    "ADBE": "Adobe Inc.",
    "TMO": "Thermo Fisher Scientific, Inc.",
    "LIN": "Linde Plc",
    "ACN": "Accenture Plc",
    "MCD": "Mcdonald's Corporation",
    "ABT": "Abbott Laboratories",
    "CSCO": "Cisco Systems, Inc.",
    "IBM": "International Business Machines Corporation",
    "GE": "Ge Aerospace",
    "PM": "Philip Morris International Inc.",
    "QCOM": "Qualcomm Inc",
    "VZ": "Verizon Communications",
    "WFC": "Wells Fargo & Co.",
    "INTU": "Intuit Inc",
    "TXN": "Texas Instruments Incorporated",
    "DHR": "Danaher Corporation",
    "NOW": "Servicenow, Inc.",
    "AMGN": "Amgen Inc",
    "ISRG": "Intuitive Surgical Inc.",
    "NEE": "Nextra Energy, Inc.",
    "CAT": "Caterpillar Inc.",
    "SPGI": "S&p Global Inc.",
    "PFE": "Pfizer Inc.",
    "DIS": "The Walt Disney Company",
    "RTX": "Rtx Corporation",
    "AMAT": "Applied Materials Inc",
    "CMCSA": "Comcast Corp",
    "T": "At&t Inc.",
    "GS": "Goldman Sachs Group Inc.",
    "UNP": "Union Pacific Corp.",
    "UBER": "Uber Technologies, Inc.",
    "PGR": "Progressive Corporation",
    "AXP": "American Express Company",
    "LOW": "Lowe's Companies Inc.",
    "TJX": "Tjx Companies, Inc.",
    "BKNG": "Booking Holdings Inc.",
    "HON": "Honeywell International, Inc.",
    "ELV": "Elevance Health, Inc.",
    "SYK": "Stryker Corporation",
    "VRTX": "Vertex Pharmaceuticals Inc",
    "BLK": "Blackrock, Inc.",
    "MS": "Morgan Stanley",
    "ETN": "Eaton Corporation, Plcs",
    "BSX": "Boston Scientific Corp.",
    "REGN": "Regeneron Pharmaceuticals Inc",
    "LMT": "Lockheed Martin Corp.",
    "COP": "Conocophillips",
    "MDT": "Medtronic Plc",
    "PLD": "Prologis, Inc.",
    "CB": "Chubb Limited",
    "ADP": "Automatic Data Processing",
    "MMC": "Marsh & Mclennan Companies, Inc.",
    "PANW": "Palo Alto Networks, Inc.",
    "ADI": "Analog Devices, Inc.",
    "SBUX": "Starbucks Corp",
    "AMT": "American Tower Corporation",
    "C": "Citigroup Inc.",
    "BX": "Blackstone Inc.",
    "TMUS": "T-Mobile Us, Inc.",
    "CI": "The Cigna Group",
    "GILD": "Gilead Sciences Inc",
    "FI": "Fiserv, Inc.",
    "DE": "Deere & Company",
    "MDLZ": "Mondelez International, Inc. Class A",
    "KLAC": "Kla Corporation",
    "MU": "Micron Technology, Inc.",
    "LRCX": "Lam Research Corp",
    "BMY": "Bristol-Myers Squibb Co.",
    "SO": "The Southern Company",
    "NKE": "Nike, Inc.",
    "SCHW": "The Charles Schwab Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "UPS": "United Parcel Service, Inc. Class B",
    "ANET": "Arista Networks",
    "DUK": "Duke Energy Corporation",
    "BA": "Boeing Company",
    "MO": "Altria Group, Inc.",
    "SHW": "The Sherwin-Williams Company",
    "CL": "Colgate-Palmolive Company",
    "ZTS": "Zoetis Inc.",
    "INTC": "Intel Corp",
    "EQIX": "Equinix, Inc. Reit",
    "TT": "Trane Technologies Plc",
    "KKR": "Kkr & Co. Inc.",
    "CME": "Cme Group Inc.",
    "WELL": "Welltower Inc.",
    "CMG": "Chipotle Mexican Grill, Inc.",
    "HCA": "Hca Healthcare, Inc.",
    "WM": "Waste Management, Inc.",
    "PH": "Parker-Hannifin Corporation",
    "APH": "Amphenol Corporation",
    "TDG": "Transdigm Group Incorporated",
    "AON": "Aon Plc Class A",
    "MCO": "Moody's Corporation",
    "SNPS": "Synopsys Inc",
    "MMM": "3m Company",
    "MSI": "Motorola Solutions, Inc.",
    "PYPL": "Paypal Holdings, Inc.",
    "CDNS": "Cadence Design Systems",
    "CVS": "Cvs Health Corporation",
    "NOC": "Northrop Grumman Corp.",
    "CTAS": "Cintas Corp",
    "PNC": "Pnc Financial Services Group",
    "TGT": "Target Corporation",
    "USB": "U.S. Bancorp",
    "GD": "General Dynamics Corporation",
    "EOG": "Eog Resources, Inc.",
    "ITW": "Illinois Tool Works Inc.",
    "BDX": "Becton, Dickinson and Co.",
    "MCK": "Mckesson Corporation",
    "ORLY": "O'reilly Automotive, Inc.",
    "CSX": "Csx Corporation",
    "FDX": "Fedex Corporation",
    "CARR": "Carrier Global Corporation",
    "AJG": "Arthur J. Gallagher & Co.",
    "ECL": "Ecolab, Inc.",
    "APD": "Air Products & Chemicals, Inc.",
    "NEM": "Newmont Corporation",
    "CEG": "Constellation Energy Corporation",
    "GEV": "Ge Vernova Inc.",
    "FCX": "Freeport-Mcmoran Inc.",
    "CRWD": "Crowdstrike Holdings, Inc. Class A",
    "NXPI": "Nxp Semiconductors N.v.",
    "ROP": "Roper Technologies, Inc.",
    "DHI": "D.R. Horton Inc.",
    "EMR": "Emerson Electric Co.",
    "MPC": "Marathon Petroleum Corporation",
    "SLB": "Schlumberger Limited",
    "PSA": "Public Storage",
    "ADSK": "Autodesk Inc",
    "AFL": "Aflac Inc.",
    "TFC": "Truist Financial Corporation",
    "MAR": "Marriot International Class A",
    "NSC": "Norfolk Southern Corp.",
    "WMB": "Williams Companies Inc.",
    "AEP": "American Electric Power Company, Inc.",
    "O": "Realty Income Corporation",
    "TRV": "The Travelers Companies, Inc.",
    "AZO": "Autozone, Inc.",
    "PSX": "Phillips 66",
    "SPG": "Simon Property Group, Inc.",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "OKE": "Oneok, Inc.",
    "COF": "Capital One Financial",
    "GM": "General Motors Company",
    "ROST": "Ross Stores Inc",
    "SRE": "Sempra",
    "ABNB": "Airbnb, Inc. Class A",
    "CCI": "Crown Castle Inc.",
    "BK": "Bank of New York Mellon Corporation",
    "DLR": "Digital Realty Trust, Inc.",
    "PCAR": "Paccar Inc",
    "ALL": "The Allstate Corporation"
};    

export function getTicker(companyName: string): string {
    // First, try an exact match
    if (name_to_ticker[companyName]) {
        return name_to_ticker[companyName];
    }

    // If no exact match, try a case-insensitive partial match
    const lowercaseCompanyName = companyName.toLowerCase();
    for (const [fullName, ticker] of Object.entries(name_to_ticker)) {
        if (fullName.toLowerCase().includes(lowercaseCompanyName)) {
            return ticker;
        }
    }

    return "Company not found in S&P 500 list";
}

export function getCompanyName(ticker: string): string {
    // Try an exact match
    if (ticker_to_name[ticker]) {
        return ticker_to_name[ticker];
    }

    return "Ticker not found in S&P 500 list";
}